spring.application.name=demo

server.port=8000

# MySQL database URL
spring.datasource.url=jdbc:mysql://localhost:3306/hr?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password=Namikadzeminato22

# Optional: Spring will automatically detect this, but you can specify it if needed
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

allowPublicKeyRetrieval=true